### ISSUE TITLE
Initial testing -- successful

### ISSUE THREAD

**Issue by banderon** [Chassis/runkit7#1]
I pulled down the extension and used my old bash method to update the php.ini template prior to provisioning just to quickly see if the VM boots up; runkit7 is loaded and functional 👍

Next step will be to try it with the php.ini Chassis extension... I'll give that a shot tomorrow.

**Comment by BronsonQuick** [comment]
@banderon Champion. Thanks so much for testing it so quickly! Glad to know the first attempt is working. I'll try the custom ini stuff tomorrow as well and see if it'll work using the `phpini` extension or if we need to add some additional logic and configuration options inside this extension. Thanks again for the speedy testing!

**Comment by banderon** [comment]
Forgot to update this issue.

The `phpini` extension worked as expected. My `custom.ini` file just needed one line:
```
extension=runkit7.so
```

That req should probably be added to the documentation.

**Comment by BronsonQuick** [comment]
Hey @banderon, I just created a PR which removes the need to use the `phpini` extension. Now a `runkit7.ini` will be [created](https://github.com/Chassis/runkit7/blob/master/modules/runkit7/manifests/init.pp#L41-L52) with `extension=runkit7.so` as the contents.
